version: '3'

services:
  database:
    container_name: 'learning_pg_master'
    image: 'postgres:latest'
    ports:
      - 3005:5432
    networks:
      - postgres-network
    volumes:
      - pg_data:/databases/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty78
      - POSTGRES_DB=learning
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: 'learning_pgadmin'
    ports:
      - 3006:80
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data/:/databases/pgadmin/
    environment:
      - PGADMIN_DEFAULT_EMAIL=keshavkjha1999@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=qwerty78

  learning_backend:
    build: .
    container_name: 'learning_backend'
    ports:
      - 3002:3000
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - .:/usr/src/app   # Mount the entire project directory
      - /usr/src/app/node_modules  # Exclude node_modules from being overridden by the local volume
    command: npm start

networks: 
  postgres-network:
    driver: bridge

volumes:
  pg_data: